### ISSUE TITLE
Database logged by mongdb_log_cimg cannot be played.

### ISSUE THREAD

**Issue by longjie** [timn/ros-mongodb_log#3]
Logging compressed image as:

```
$ rosrun mongodb_log mongodb_log.py /left/image_raw/compressed
Adding topic /left/image_raw/compressed
DETECTED compressed image topic /left/image_raw/compressed, using fast C++ logger
^Ctajima@nextage1:~/Codes/ros/hydro/src/mongodb_store/mongodb_log/src$ rrun mongodb_log mongodb_log.py /left/image_raw/compressed
Adding topic /left/image_raw/compressed
WARNING: topic [/left/image_raw/compressed] does not appear to be published yet
DETECTED compressed image topic /left/image_raw/compressed, using fast C++ logger
```

And playing it back as:

```
$ rosrun mongodb_store mongodb_play.py /left/image_raw/compressed
Playing back topics set([u'left_image_raw_compressed'])
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tajima/Codes/ros/hydro/src/mongodb_store/mongodb_store/scripts/mongodb_play.py", line 116, in queue_from_db
    self.publisher = rospy.Publisher(documents[0]["_meta"]["topic"], msg_cls, latch = documents[0]["_meta"]["latch"], queue_size = 10)
KeyError: 'topic'
```

The database has no _meta: {topic, latch} field, I guess that's why.

Environment: Ubuntu12.04 + Hydro, mongodb_store ver. 0.1.12

Thank you.

**Comment by jeremy-a** [comment]
I have the exact same error but on Ubuntu 14.04 + Indigo using mongod ver2.4.9. Any updates?

**Comment by marc-hanheide** [comment]
see https://github.com/strands-project/mongodb_store/issues/123 for further discussion

**Comment by hawesie** [comment]
Also, for the record, this repo is out of date, and the developed version which is released in binary by ROS is at: https://github.com/strands-project/mongodb_store/tree/hydro-devel/mongodb_log so issues should be raised at https://github.com/strands-project/mongodb_store/issues
